config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  namespace :users do
    resource :oauth_email_confirmations, only: %i[new create]
  end

  concern :votable do
    member do
      put :vote_plus
      put :vote_minus
      delete :cancel
    end
  end

  concern :commentable do
    resource :comments, only: :create
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end


  post '/answers/:id', to: 'answers#mark_as_best', as: 'mark_as_best'
  delete '/answers/:id/files/:file_id', to: 'answers#delete_file', as: 'answer_delete_file'
  delete '/questions/:id/files/:file_id', to: 'questions#delete_file', as: 'question_delete_file'
  get '/users/:id/rewards', to: 'users#rewards', as: 'user_rewards'
  root to:"questions#index"
  resources :search, only: :index

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, as: :linkable, dependent: :destroy
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files

  validates :title, :body, presence: true

  def delete_file(file_id)
    files.where(id: file_id).purge_later
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  skip_authorization_check

  before_action :find_question, only: %i[show update destroy]

  def index
    authorize! :read, Question
    @questions = Question.includes(:answers)
    render json: @questions
  end

  def show
    authorize! :read, Question
    render json: @question, serializer: QuestionOneSerializer
  end

  def create
    authorize! :create, Question
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question, status: :created
    else
      render json: {errors: @question.errors}, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @question

    if @question.update(question_params)
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @question

    @question.destroy
    render json: { messages: ["Question was successfully deleted."] }
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted 
  before_action :authenticate_user!, except: [:index, :show]
  before_action :question, except: [:index]
  before_action :set_gon, only: [:show]
  after_action :publish_question, only: %i[create]
  before_action :subscription, only: %i[show update]

  authorize_resource
  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def edit
    @question.links.new
    @question.reward.present? ? @question.reward : @question.build_reward
  end

  def create
    question.update(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created'
    else
      render :new, notice: 'Your question not created'
    end
  end

  def update
    question.update(question_params.merge(user: current_user))
    render layout: false
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def delete_file
    @question.delete_file(params[:file_id])
    redirect_to question_path(@question)
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: {
          question: @question,
          current_user: current_user
        }
      )
    )
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(:title, :body, :id, files: [], links_attributes: %i[id name url _destroy], reward_attributes: %i[id title image _destroy])
  end

  def set_gon
    gon.question_id = @question.id
    gon.current_user_id = current_user&.id
  end

  def subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_files.slim
div.files
  -if @question.files.attached?
    -@question.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      = link_to 'Delete file', question_delete_file_path(id: @question.id, file_id: file.id), method: :delete, remote: false

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association 'Remove link', f

app/views/questions/_question.slim
=link_to question.title, question
br
=question.body
br

app/views/questions/index.slim
- cache collection_cache_key_for: @questions do
  .questions-list
    = render @questions
  - if can?(:create, Question)
    p=link_to 'Ask question', new_question_path
- if current_user.present?
  p=button_to 'Log out', destroy_user_session_path, method: :delete
- unless current_user.present?
  p=button_to 'Log in', new_user_session_path, method: :get

app/views/questions/new.slim
= render 'shared/errors', resource: @question

= form_with model: @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  .links
    = f.fields_for :links do |link|
      == render 'link_fields', f: link
    .link
      = link_to_add_association 'Add link', f, :links
  p Rewards:
  .reward
    p
      = f.fields_for :reward do |reward|
        = reward.label :title, 'Reward name'
        br
        = reward.text_field :title
        br
        = reward.label :image, 'Reward'
        br
        = reward.file_field :image, direct_upload: true
  = f.submit 'Ask'

app/views/questions/show.slim
.question
  .subscription
    - if can?(:create, Subscription)
      = render 'subscriptions/subscription', resource: @question
  = render 'files', resource: @question
  .question-errors
    = render 'shared/errors', resource: @question
  -cache @question do
    h1=@question.title
    p.question-body= @question.body
    div class="question-id-#{@question.id}-comments comments"
      p Comments:
      - if @question.comments.any?
        = render @question.comments
      - if current_user.present?
        p New Comment:
        = render 'comments/new', resource: @question
    .links
      =render 'shared/render_links', resource: @question
    .rewards
      =render 'shared/render_rewards', resource: @question
    = render 'shared/vote', resource: @question
  br
  - if current_user&.author?(@question)
    p = button_to 'Delete question',question_path(@question), method: :delete
    = link_to 'Edit', '#', class: 'edit-question-link'
    = form_with model: @question, class: 'hidden', id: "edit-question", local: false, method: :patch do |f|
      = f.label :title
      = f.text_field :title
      = f.label :body
      = f.text_area :body
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
      p Links:
      .links
        = f.fields_for :links do |link|
          == render 'link_fields', f: link
        .link
          = link_to_add_association 'Add link', f, :links
      p Rewards:
      .reward
        p
          = f.fields_for :reward do |reward|
            = reward.label :title, 'Reward name'
            br
            = reward.text_field :title
            br
            = reward.label :image, 'Reward'
            br
            = reward.file_field :image, direct_upload: true
      = f.submit 'Save'
br
-if current_user.present?
  .answer-errors
    = render 'shared/errors', resource: @answer

  = form_with model: [@question, @answer], class: 'new-answer', local: false do |f|
    = f.label :body, 'New answer'
    = f.text_area :body
    = f.label :files
    = f.file_field :files, multiple: true
    p Links:
    .links
      = f.fields_for :links do |link|
        == render 'link_fields', f: link
      .link
        = link_to_add_association 'Add link', f, :links
    = f.submit 'Create'

.answers
  =render @question.answers.order(best: :desc)

app/views/questions/update.js.erb
<% if @question.persisted? %>
    $('.question-errors').html('<%= render 'shared/errors', resource: @question %>');
    $('h1').html('<%= @question.title %>');
    $('.question-body').html('<%= @question.body %>');
    $('.question>.files').html('<%= render 'files', resource: @question %>');
    $('.question>.links').html('<%= render 'shared/render_links', resource: @question %>');
    $('.question>.rewards').html('<%= render 'shared/render_rewards', resource: @question %>');
    $('form#edit-question').addClass('hidden');
    updateQuestions()
    $('.edit-question-link').show();

<% end %>