config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  namespace :users do
    resource :oauth_email_confirmations, only: %i[new create]
  end

  concern :votable do
    member do
      put :vote_plus
      put :vote_minus
      delete :cancel
    end
  end

  concern :commentable do
    resource :comments, only: :create
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end


  post '/answers/:id', to: 'answers#mark_as_best', as: 'mark_as_best'
  delete '/answers/:id/files/:file_id', to: 'answers#delete_file', as: 'answer_delete_file'
  delete '/questions/:id/files/:file_id', to: 'questions#delete_file', as: 'question_delete_file'
  get '/users/:id/rewards', to: 'users#rewards', as: 'user_rewards'
  root to:"questions#index"
  resources :search, only: :index

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check

  def index
    @results = SearchService.call(query_params)
  end

  private

  def query_params
    params.permit(:query, :scope, :commit)
  end
end

app/views/search/_answer.slim
p = resource.body

app/views/search/_comment.slim
p = resource.body

app/views/search/_form.slim
= form_with url: search_index_path, method: :get, local: true do |f|
  = f.label :query
  = f.text_area :query
  = f.label :scope
  = f.select :scope, options_for_select([%w(All thinking_sphinx),
                                           %w(Question question),
                                           %w(Answer answer),
                                           %w(Comment comment),
                                           %w(User user)])
  = f.submit 'Search'

app/views/search/_question.slim
p = resource.title
p = resource.body

app/views/search/_user.slim
p = resource.email

app/views/search/index.html.slim
h1 Search results:
-if !@results.empty?
  - @results.each do |result|
    = render partial: result.class.to_s.downcase, locals: { resource: result }
-else
  h2 Nothing found
p= link_to 'Back to Questions', questions_path