config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  namespace :users do
    resource :oauth_email_confirmations, only: %i[new create]
  end

  concern :votable do
    member do
      put :vote_plus
      put :vote_minus
      delete :cancel
    end
  end

  concern :commentable do
    resource :comments, only: :create
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end


  post '/answers/:id', to: 'answers#mark_as_best', as: 'mark_as_best'
  delete '/answers/:id/files/:file_id', to: 'answers#delete_file', as: 'answer_delete_file'
  delete '/questions/:id/files/:file_id', to: 'questions#delete_file', as: 'question_delete_file'
  get '/users/:id/rewards', to: 'users#rewards', as: 'user_rewards'
  root to:"questions#index"
  resources :search, only: :index

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  belongs_to :question, touch: true
  belongs_to :user
  validates :body, presence: true
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files
  def mark
    best = question.answers.where(best: true)
    unless best.first == self
      best.update(best: false)
      self.update(best: true)
    end
    question.reward.update(user: user) if question.reward.present?
  end

  def delete_file(file_id)
    files.where(id: file_id).purge_later
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: %i[create publish_answer]
  before_action :find_answer, only: %i[destroy update mark_as_best delete_file]
  after_action :publish_answer, only: :create

  authorize_resource

  def new
    @answer = Answer.new
    render 'questions/show'
  end

  def create
    @answer = @question.answers.create(answer_params.merge(user: current_user))
    render layout: false
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
        "question/#{@question.id}/answers",
        hash_for_cable
    )

    send_notif
  end

  def send_notif
    SendNewAnswerJob.perform_later(@answer, @answer.question)
  end
  def hash_for_cable
    hash = {
      answer: @answer,
      rating: @answer.rating,
      links: @answer.links,
      question_author: @question.user,
      files: []
    }
    if @answer.files.attached?
      @answer.files.each_with_index do |file, i|
        hash[:files][i] = {
          id: file.id,
          name: file.filename.to_s,
          url: url_for(file)
        }
      end
    end
    hash
  end
  def update
    @answer.update(answer_params.merge(user: current_user))
    render layout: false
  end

  def destroy
    @answer.destroy
    @question = @answer.question
    render layout: false
  end

  def mark_as_best
    @answer.mark
    @question = @answer.question
    render layout: false

  end

  def delete_file
    @answer.delete_file(params[:file_id])
    redirect_to question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  skip_authorization_check

  before_action :find_question, only: %i[index create]
  before_action :find_answer, only: %i[show update destroy]

  def index
    authorize! :index, Answer
    render json: @question.answers
  end

  def show
    authorize! :show, Answer
    render json: @answer, serializer: AnswerOneSerializer
  end

  def create
    authorize! :create, Answer
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, Answer

    if @answer.update(answer_params)
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @answer

    @answer.destroy
    render json: { messages: ["Answer was successfully deleted."] }
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- unless answer.new_record?
  - cache answer do
    div class="answer-#{answer.id}" data={best: "#{answer.best}"}
      p= answer.body
      = render 'shared/vote', resource: answer
      .links
        =render 'shared/render_links', resource: answer
      - if answer.best
        p.best= "The best"
      = render partial: 'answers/files', locals: {answer: answer}
      - if current_user&.author?(answer.question)
        = button_to 'Mark as best', mark_as_best_path(answer), method: :post, remote: true
      - if current_user&.author?(answer)
        = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        = button_to 'Delete answer', answer_path(answer), remote: true, method: :delete
        = form_with model: answer, class: 'hidden', id: "edit-answer-#{answer.id}", local: false, method: :patch do |f|
          = f.label :body, "Your answer"
          = f.text_area :body
          = f.label :files
          = f.file_field :files, multiple: true
          p Links:
          .links
            = f.fields_for :links do |link|
              == render 'link_fields', f: link
            .link
              = link_to_add_association 'Add link', f, :links
          = f.submit 'Save', id: 'new-answer-submit'
    br
    div class="answer-id-#{answer.id}-comments comments"
      p Comments:
      -if answer.comments.any?
        = render answer.comments
    p New Comment:
    = render 'comments/new', resource: answer

app/views/answers/_files.slim
div.files
  -if answer.files.attached?
    -answer.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      - if current_user&.author?(answer)
        = link_to 'Delete file', answer_delete_file_path(id: answer.id, file_id: file.id), class: 'delete_file', method: :delete, remote: false

app/views/answers/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association 'Remove link', f

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% if @answer.persisted? %>
$('.answers').append('<%= j render @answer %>');
$('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render @question.answers.order(best: :desc) %>');

app/views/answers/update.js.erb
<% if @answer.persisted? %>
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
$('.answer-<%=@answer.id %>')[0].firstChild.innerHTML = '<%= @answer.body %>';
$('.answer-<%=@answer.id %>>.files').html('<%= render partial: 'answers/files', locals: {answer: @answer} %>');
$('.answer-<%=@answer.id %>>.links').html('<%= render partial: 'shared/render_links', locals: {resource: @answer} %>');
$('#edit-answer-<%=@answer.id %>').addClass('hidden');
updateAnswers();
$('.edit-answer-link[data-answer-id="<%=@answer.id %>"]').show();

<% end %>