config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {omniauth_callbacks: 'oauth_callbacks'}

  namespace :users do
    resource :oauth_email_confirmations, only: %i[new create]
  end

  concern :votable do
    member do
      put :vote_plus
      put :vote_minus
      delete :cancel
    end
  end

  concern :commentable do
    resource :comments, only: :create
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end


  post '/answers/:id', to: 'answers#mark_as_best', as: 'mark_as_best'
  delete '/answers/:id/files/:file_id', to: 'answers#delete_file', as: 'answer_delete_file'
  delete '/questions/:id/files/:file_id', to: 'questions#delete_file', as: 'question_delete_file'
  get '/users/:id/rewards', to: 'users#rewards', as: 'user_rewards'
  root to:"questions#index"
  resources :search, only: :index

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def create
    @question = Question.find(params[:question_id])
    @subscription = @question.subscriptions.create(user: current_user)
    render layout: false
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    render layout: false
  end
end

app/views/subscriptions/_subscription.slim
-if current_user&.subscribed_of?(resource)
  p= link_to "Unsubscribe", subscription_path(@subscription), method: :delete,  remote: true
- else
  p= link_to "Subscribe", question_subscriptions_path(resource), method: :post,  remote: true

app/views/subscriptions/create.js.erb
$('.subscription').html('<%= j render 'subscriptions/subscription', resource: @question %>')

app/views/subscriptions/destroy.js.erb
$('.subscription').html('<%= j render 'subscriptions/subscription', resource: @subscription.question %>');